services:
  mysql:
    image: mysql:8.0
    container_name: mysql-spring
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springdb
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: